config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'posts#index'

  resources :posts do
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  validates :image, presence: true

  has_attached_file :image, styles: { medium: '640x' }

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :user_name, presence: true, length: { minimum: 4, maximum: 12 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      flash[:notice] = 'Nice comment!'
      redirect_to root_path
    else
      flash[:alert] = 'Check the coment form, something went wrong'
      render root_path
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])

    if @comment.user_id == current_user.id
      @comment.delete
      flash[:notice] = 'Comment deleted.'
      redirect_to root_path
    else
      flash[:warning] = "That doesn't belong to you!"
      redirect_to root_path
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_owner

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :owned_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'Your post has been created.'
      redirect_to @post
    else
      flash[:alert] = 'Halt, you fiend! You need an image to post here!'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = 'Post updated hombre.'
      redirect_to root_path
    else
      flash[:alert] = 'Something is wrong with your form!'
      redirect_to root_path
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'Problem solved!  Post deleted.'
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:caption, :image)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def owned_post
    unless @post.user.id == current_user.id
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end  

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
#comment
  .user-name
    = comment.user.user_name
  .comment-content
    = comment.content
  - if comment.user == current_user
    = link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" }, id: "delete-#{comment.id}" do
      %span(class="glyphicon glyphicon-remove delete-comment")

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Photogram
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .navbar-container
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle Navigation
            %span.icon-bar
            %span.icon-bar
          .navbar-brand= link_to "Photogram", root_path
        .collapse.navbar-collapse#bs-navbar-collapse-1
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li
                = link_to "New Post", new_post_path
              %li
                = link_to "Logout", destroy_user_session_path, method: :delete
            - else
              %li
                = link_to "Login", new_user_session_path
              %li
                = link_to "Register", new_user_registration_path

    .container
      -flash.each do |name, msg|
        = content_tag :div, msg, class: [:alert, alert_for(name)]
      = yield

app/views/posts/_post.html.haml
.posts-wrapper
  .post
    .post-head
      .thumb-img
      .user-name
        = post.user.user_name
      .time-ago
        = time_ago_in_words post.created_at
    .image.center-block
      = link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post)
    .post-bottom
      .caption
        .caption-content
          .user-name
            = post.user.user_name
          = post.caption
        .comments{id: "comments_#{post.id}"}
          - if post.comments
            = render post.comments, post: post
    .comment-like-form.row
      .like-button.col-sm-1
        %span(class="glyphicon glyphicon-heart-empty")
      .comment-form.col-sm-11
        = form_for([post, post.comments.build]) do |f|
          = f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}"
          = submit_tag("Submit")

app/views/posts/edit.html.haml
.text-center
  = image_tag @post.image.url(:medium)
.form-wrapper
  = simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f|
    .form-group
      = f.input :image
    .form-group.text-center
      = f.input :caption
    .form-group.text-center
      = f.button :submit, class: 'btn-success'
.text-center.edit-links
  = link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }
  |
  = link_to "cancel", posts_path

app/views/posts/index.html.haml
.posts-wrapper.row
  -@posts.each do |post|
    = render 'post', post: post

app/views/posts/new.html.haml
.form-wrapper
  = simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f|
    .form-group
      = f.input :image
    .form-group.text-center
      = f.input :caption
    .form-group.text-center
      = f.button :submit, class: 'btn-success'

app/views/posts/show.html.haml
= render 'post', post: @post
.text-center.edit-linkss
  - if @post.user.id == current_user.id
    = link_to 'Cancel', posts_path
    |
    = link_to 'Edit Post', edit_post_path(@post)
  - else
    = link_to 'Cancel', posts_path